/*

we are going to program a game “Rock, Paper & Scissor.”

For this task, we will use library time.h. The header file time.h contains definitions of functions to get and manipulate date and time information in our program. You also have to generate a random number for this program, so the following is the code to generate a random number.

int generateRandomNumber(int n)
{
srand(time(NULL));
return rand() % n;
}

The function srand() is used to initialize the random number generator by passing the argument seed. We can use srand() function is defined inside stdlib.h header file. The main will look like:
Problem statement:-

As we all are familiar with the concept of the game. In this game, we have two players. In our program, player 1 will be the user, and player 2 will be the computer. Player 1 selects either rock, paper, or scissor. The computer does not know about what player 1 has selected, so the computer randomly selects any item (rock, paper, or scissor).

In this game, each player has 3 turns. The player who gets the point at least two times will win the game. The following are the rules of the game.

rock vs. scissors -> rock wins
paper vs. scissors -> scissors wins
paper vs. rock -> paper wins
Task:-

You have to write a C program that will:

    Allows the user to play this game three times with a computer.
    Log the scores of the computer and the player.
    Display the name of the winner at the end

Note: You have to display the name of the player during the game. Take users name as an input from the user.

*/

#include <stdio.h>
#include <stdlib.h>
#include <time.h>

/*
int main(){
    srand(time(NULL));  // srand takes seed as input and define inside stdlib.h
    printf("The Random Number Generated By Computer Between 0 to 100 is %d\n", rand()%100);
    return 0;
}
*/

/*
int generateRand(int i){
    srand(time(NULL));
    printf("The Random Number Generated By Computer Between 0 to %d is %d\n", i, rand()%i);
    return 0;
}

int main(){
    int randVal = generateRand(3);
    return 0;
}
*/

int main(){
    int j, k = 0, l = 0;
    char name[34];
    printf("Enter The Name Of The Player :-\n");
    gets(name);
    printf("Hello %s, Welcome To My Rock, Paper, Scissors Game\n\n", name);

    printf("RULES :-\nPress 0 To Select Rock\nPress 1 To Select Paper\nPress 2 To Select Scissor\n5 Rounds In This Game\nThe One Who Has More Points Will Be Win The game\n\n");

    for(int i = 1; i <= 5; i++){
        int ptr[i];
        printf("%s, Enter The %d Round Number\n", name, i);
        scanf("%d", &j);
        printf("%s Entered The %d Number\n\n", name, j);
        printf("Chitti, Enter The Number\n");
        srand(time(NULL));
        ptr[i] = rand()%3;
        printf("Chitti, Entered The %d Number\n\n", ptr[i]);
        
        if(j == 0 && ptr[i] == 0){
            printf("%s and Chitti Both selected Rock\n%d Round is Tie\n\n", name,i);
        }
        else if(j == 0 && ptr[i] == 1){
            printf("%s selected Rock and Chitti selected Paper\n%d Round is Chitti Win\n\n", name, i);
            k++;
        }
        else if(j == 0 && ptr[i] == 2){
            printf("%s selected Rock and Chitti selected Scissor\n%d Round is %s Win\n\n", name, i, name);
            l++;
        }
        else if(j == 1 && ptr[i] == 0){
            printf("%s selected Paper and Chitti selected Rock\n%d Round is %s Win\n\n", name, i, name);
            l++;
        }
        else if(j == 1 && ptr[i] == 1){
            printf("%s and Chitti Both selected Paper%d Round is Tie\n\n", name, i);
        }
        else if(j == 1 && ptr[i] == 2){
            printf("%s selected Paper and Chitti selected Scissor\n%d Round is Chitti Win\n\n", name, i);
            k++;
        }
        else if(j == 2 && ptr[i] == 0){
            printf("%s selected Scissor and Chitti selected Rock%d Round is Chitti Win\n\n", name, i);
            k++;
        }
        else if(j == 2 && ptr[i] == 1){
            printf("%s selected Scissor and Chitti selected Paper\n%d Round is %s Win\n\n", name, i, name);
            l++;   
        }
        else if(j == 2 && ptr[i] == 2){
            printf("%s and Chitti Both selected Scissor\n%d Round is Tie\n\n", name, i);
        }
    }

    if(k < l){
        printf("\nCongratulation, %s Win The Game.\nYou Win %d Round\n", name, l);
    }
    else if(k > l){
        printf("\nSorry, %s Lost The Game.\nYou Win %d Round\n", name, l);
    }
    else{
        printf("\nThe Game is Tie\n");
    }

    printf("\nThanks For Playing, %s\n\n", name);
    return 0;
}