version: "3.4"

services:
  postgres:
    container_name: postgresql
    image: postgres
    ports:
      - 5434:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: chats
      POSTGRES_PASSWORD: chats
  redis:
    container_name: redis
    image: redis/redis-stack:latest
    ports:
      - 6379:6379
      - 8001:8001
  zookeeper:
    container_name: zookeeper
    image: zookeeper
    ports:
      - 2181:2181
  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: 192.168.234.202:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.234.202:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

volumes:
  postgres_data: